### ISSUE TITLE
AuthService 리팩토링

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/coupang-clone-2#1]
#### 세부 사항
- AuthService는 인증 관련 비즈니스 로직들을 다루는 모듈
- 코드는 아래와 같다.

```jsx
class AuthService {
  /** refreshToken을 이용해 새로운 토큰을 발급받습니다. */
  async refresh() {
    const refreshToken = cookies.get("refreshToken");
    if (!refreshToken) {
      return;
    }

    const { data } = await axios.post(
      process.env.NEXT_PUBLIC_API_HOST + "/auth/refresh",
      null,
      {
        headers: {
          Authorization: `Bearer ${refreshToken}`,
        },
      }
    );

    cookies.set("accessToken", data.access, { expires: 1 });
    cookies.set("refreshToken", data.refresh, { expires: 7 });
  }

  /** 새로운 계정을 생성하고 토큰을 발급받습니다. */
  async signup(
    email: string,
    password: string,
    name: string,
    phoneNumber: string,
    agreements: SignupAgreements
  ) {
    const { data } = await axios.post(
      process.env.NEXT_PUBLIC_API_HOST + "/auth/signup",
      { email, password, name, phoneNumber, agreements }
    );

    cookies.set("accessToken", data.access, { expires: 1 });
    cookies.set("refreshToken", data.refresh, { expires: 7 });
  }

  /** 이미 생성된 계정의 토큰을 발급받습니다. */
  async login(email: string, password: string) {
    const { data } = await axios.post(
      process.env.NEXT_PUBLIC_API_HOST + "/auth/login",
      { email, password }
    );

    cookies.set("accessToken", data.access, { expires: 1 });
    cookies.set("refreshToken", data.refresh, { expires: 7 });
  }
}

export default new AuthService();
```

- 재사용성, 확장성을 고려해 모듈화.
- 추가된 UserService와, 이후 추가될 수 있을 OrderService, ItemService 등을 편하고 직관적으로 대응할 수 있도록, 하나의 부모클래스를 extend 하는 방법으로 구현.

#### 어떻게 해결 할것인가
- 외부라이브러리 관련 코드의 결합도를 낮추기 위해 분리 및 모듈화를 한다. (axios 관련)
- cookie를 다루는 로직을 모듈화한다.
- 이름을 신중히 고려해서 명명한다.
- Service(서버와 data fetching 관련 코드) 부모클래스 추상화에 대해 고민한다.

#### ToDo List
- [x] axios 코드 분리
- [x] cookie 코드 분리
- [x] service 클래스 추상화
- [x] 적용
- [x] 최종 리팩터링 및 pr
